### ISSUE TITLE
Chore: Add a Table Of Content

### ISSUE THREAD

**Issue by jammutkarsh** [Anmol-Baranwal/Cool-GIFs-For-Readme#3]
This is an awesome **_long_** list, it was hard to scroll up and down.

I think a TOC like [this](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects#menu) would be very helpful in navigation!

**Comment by Anmol-Baranwal** [comment]
@JammUtkarsh 
Thanks for creating an issue.

Sure, I will add a menu, but it might not solve the complete issue because naming is done by me, and it is based on personal preference, which might not be the best way to categorize something. Also, the ones below won't load unless the above GIFs are loaded, so it will be more or less the same thing.

I will add the menu in 48 hours and will close this issue after informing you.

> I won't add the name of every GIF; rather, just the major categories.

**Comment by Anmol-Baranwal** [comment]
@JammUtkarsh
I got caught up in something else, causing a delay.

Nevertheless, I have now added the menu and a button to scroll to the top on each link, making navigation easier.

> Let me know if you need anything else. Thanks again for creating the issue. 

I'm closing the issue for now.
